# fly.toml app configuration file generated for portkey-demo on 2024-02-20T18:26:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portkey-demo'
primary_region = 'ams'

[env]
  HOST = '0.0.0.0'
  METRICSHOST = '0.0.0.0'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[metrics]
  port = 3030
  path = "/metrics"

[[vm]]
  size = 'shared-cpu-1x'

[http_service.http_options.response.headers]
  Strict-Transport-Security = 'max-age=31536000; includeSubDomains'
  Content-Security-Policy = "default-src 'self' analytics.thisismy.cloud;"
  X-Frame-Options = 'SAMEORIGIN'
  X-Content-Type-Options = 'nosniff'
  Referrer-Policy = 'strict-origin-when-cross-origin'
  Permissions-Policy = "geolocation=(), microphone=(), camera=(), fullscreen=(self), payment=()"