# fly.toml app configuration file generated for portkey-demo on 2024-02-20T18:26:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portkey-demo'
primary_region = 'ams'

[experimental]
  cmd = ['--config-path', '/config']

[build]

[[mounts]]
  source = 'portkey_config'
  destination = '/config'
  initial_size = '1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
