name: Run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main, 'feature/**' ]
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Cache Go modules and build
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.cache/go-build
          ~/go
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go test -v ./... -coverprofile=coverage.out

    - name: Build assets
      if: startsWith(matrix.os, 'ubuntu') == true
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 26
        cache: 'npm'
    - if: startsWith(matrix.os, 'ubuntu') == true
      run: npm ci --ignore-scripts
    - if: startsWith(matrix.os, 'ubuntu') == true
      run: npm run build
